language: python
python:
  - "3.5"
  - "3.6"
#  - "3.7-dev"

install:
  - "pip install pipenv"
  - "pipenv install --dev --deploy"
  - "python -m nltk.downloader all"

script:
  - "python setup.py test"
  - "pytest --doctest-plus"
